CREATE TABLE IF NOT EXISTS files (
    id BIGINT NOT NULL PRIMARY KEY,
    mime TEXT NOT NULL,
    extension TEXT NOT NULL,
    size BIGINT NOT NULL,
    hash CHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS file_metadata (
    id BIGINT NOT NULL PRIMARY KEY REFERENCES files(id) ON DELETE CASCADE,
    width BIGINT,
    height BIGINT,
    duration BIGINT,
    line_count BIGINT
);

CREATE TABLE IF NOT EXISTS posts (
    id CHAR(32) NOT NULL PRIMARY KEY,
    description TEXT,
    uploaded_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP,
    expires_at TIMESTAMP,
    views BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS post_attachments (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    post_id CHAR(32) NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS storages (
    id CHAR(64) PRIMARY KEY,
    data LONGTEXT NOT NULL
);